stages:          # List of stages for jobs, and their order of execution
  - check-deps
  - trivy

deps-job:       # This job runs in the build stage, which runs first.
  stage: check-deps
  before_script:
    - apk update
    - apk add python3
    - apk add py3-pip
    - apk add tar
    - apk add  nodejs npm
    - wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
    - tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz
    - export PATH=$PATH:/usr/local/go/bin
  script: python3 dependencies.py $CI_PROJECT_REPOSITORY_LANGUAGES > deps.txt
  artifacts:
    paths:
    - deps.txt

trivy_test:
  stage: trivy
  image: ubuntu
  
  before_script:
    - apt-get update
    - apt-get install wget -y
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
    - dpkg -i trivy_0.29.2_Linux-64bit.deb
  script: trivy fs $CI_PROJECT_DIR > trivy_check.txt
  artifacts:
    paths:
    - trivy_check.txt
